import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Profile from '../../public/profilePic.jpg'
import Link from "next/link";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });


  return (
    <>
      <Head>
        <title>Gingerpeer | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/G200.png" />
      </Head>
      <main className="p-10">
        <h1 className="text-3xl md:text-6xl text-center text-purple-500"><em className='text-cyan-400'>&lt;</em> Pierre Daniel van Zyl <em className='text-cyan-400'>/&gt;</em></h1>
        <br/>
        <h2 className="mb-5 text-xl text-center md:text-3xl">FullStack React Engineer</h2>
        
        <div className="md:flex lg:flex-row">
          <article className="mb-10 md:basis-1/2 p-2 mr-1 lg:ml-20">
            {/* <span className="md:hidden float-right mt-10 pl-2">
              <Image className="rounded" width={100} height={125} src={Profile} alt="Pierre van Zyl Picture" />
            </span> */}
            <p className="mt-7 mb-7">Hi there.<br/> My name is Pierre van Zyl I am a software engineer specializing in the T3 stack. <br/>Ie. TypeScript, Next.js, tRCP, React Query, Tailwind.css & PostgreSql.</p>
            <p className="mt-7">I build web applications, mobile applications, e-commerce websites and landing pages. Building your specific product and meeting your individual needs is what I strive for, all whilst ensuring that you get a beautifully designed, fully functional and secure application.</p>
            <p className="mt-7">My specialization in Next.js inevitably results in my expertise in React.js which I use to build both Web Based and Mobile Base Applications with either Next.js, React or React Native.
            </p>
            <p className="mt-7">I would love to connect with you, and start the adventure of building your application.</p>
             <div className="font-extrabold text-transparent text-5xl bg-clip-text bg-gradient-to-r from-purple-500 to-cyan-300 text-center mt-20 animate-bounce hover:animate-none" >
                <Link href="/contact">Contact me</Link>
             </div>  
          </article>
          <span className="md:basis-1/2 mt-12 lg:mr-20 sm:ml-5">
            <Image className="rounded" layout="responsive" width={400} height={500} src={Profile} alt="Pierre van Zyl Picture" />
          </span>
        </div>
        
      {/* <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> 
        <AuthShowcase /> */}
      </main>
    </>
  );
};

export default Home;
