import React from 'react'
import Image from 'next/image' 
import Logo from '../../public/G500.png'
import Link from 'next/link'
import Head from 'next/head'


export default function Layout({children}:{children: React.ReactNode}) {
  return (
    <div className='bg-black text-white'>
    <div className='nav'>
      <Head>
        <title>Gingerpeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/G200.png" />
      </Head>
      <div className='navBrand'>
        <Image
          src={Logo}
          alt="Gingerpeer Logo"
          width={75}
          height={75}
        />
      </div>
      <div className='navLinks'>
        <Link href='/'>Home</Link>
        <Link href='/about'>About</Link>
        <Link href='/work'>My Work</Link>
        <Link href='/contact'>Contact Me</Link>
        <Link href='/blog'>Blog</Link>
      </div>
      </div>
      <div className='colorLine'></div>
      {children}
      <div className='footer'>
        <em>Copyright &copy; Pierre Daniel van Zyl 2022</em>
      </div>
    </div>
  )
}
