import React, { useState } from 'react'
import Image from 'next/image' 
import Logo from '../../public/G500.png'
import Link from 'next/link'
import Head from 'next/head'
import { Socials } from './Socials'


export default function Layout({children}:{children: React.ReactNode}) {
  const [ showMenu, setShowMenu ] = useState("hidden absolute right-9 md:flex md:mx-auto md:items-center md:w-auto md:space-x-6")
  return (
    <div className='bg-white text-black dark:bg-black dark:text-white min-h-screen'>
      <Head>
        <title>Gingerpeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="57x57" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/G200.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/G200.png" />
        <link rel="icon" sizes="192x192" href="/G200.png" />
        <link rel="icon" sizes="32x32" href="/G200.png" />
        <link rel="icon" sizes="96x96" href="/G200.png" />
        <link rel="icon" sizes="16x16" href="/G200.png" />
        <link rel="icon" type='image/png' href="/G500.png" />
      </Head>
      <div className='relative px-4 py-4 flex justify-between items-center bg-black'>
        <div className='flex items-center flex-shrink-0 text-white mr-6'>
          <Image
            className='fill-current h-8 w-8 mr-2'
            src={Logo}
            alt="Gingerpeer Logo"
            width={75}
            height={75}
          />
      </div>
        <div className='md:hidden'>
          <button className='absolute right-9 top-9' onClick={()=> showMenu === "hidden absolute right-9 md:flex md:mx-auto md:items-center md:w-auto md:space-x-6" ? setShowMenu("mt-20 mr-5") : setShowMenu("hidden absolute right-9 md:flex md:mx-auto md:items-center md:w-auto md:space-x-6")}>
             <hr className='my-2 mx-auto w-10 h-0.5 bg-purple-600 rounded border-0 dark:bg-purple-600' />
             <hr className='my-2 mx-auto w-10 h-0.5 bg-purple-600 rounded border-0 dark:bg-purple-600' />
             <hr className='my-2 mx-auto w-10 h-0.5 bg-purple-600 rounded border-0 dark:bg-purple-600' />
          </button>
        </div>
        <div className=''>
          <div className={`${showMenu}`}>
            <Link href='/'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>Home</a></Link>
            <Link href='/about'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>About</a></Link>
            <Link href='/work'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>My Work</a></Link>
            <Link href='/contact'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>Contact Me</a></Link>
            {/* <Link href='/blog'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>Blog</a></Link>
            <Link href='/admin'><a className='block text-right text-md text-cyan-300 hover:text-purple-500'>Admin</a></Link> */}
          </div>
        </div>
      </div>
      <hr className='my-2 mx-auto text-transparent h-1 bg-gradient-to-r from-purple-500 via-purple-500 to-cyan-300 mb-10 animate-pulse'/>
      {children}
      
      <Socials />
      <div className='sticky top-[100vh] p-5 text-right text-xs text-transparent bg-clip-text bg-gradient-to-r from-purple-500 to-cyan-300'>
        <em className='pt-5'>Copyright &copy; 2022 | Pierre van Zyl </em>
      </div>
    </div>
  )
}
